import 'package:game_core/game_core.dart';

/// Dashy's store content (GAME_IDEAS.md §5.6): character skins, trails, and
/// backgrounds.
final StoreCatalog dashyCatalog = StoreCatalog(
  categories: const [
    StoreCategory(id: 'characters', nameKey: 'tabCharacters', slot: CosmeticSlot.character),
    StoreCategory(id: 'trails', nameKey: 'tabTrails', slot: CosmeticSlot.effect),
    StoreCategory(id: 'backgrounds', nameKey: 'tabBackgrounds', slot: CosmeticSlot.background),
  ],
  cosmetics: const [
    Cosmetic(
      id: 'character_classic',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticClassic',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/character_classic.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'character_cat',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticCatBall',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/character_cat.png',
      priceGems: 180,
    ),
    Cosmetic(
      id: 'character_robot',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticRobotBall',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/character_robot.png',
      priceGems: 280,
    ),
    Cosmetic(
      id: 'character_watermelon',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticWatermelon',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/character_watermelon.png',
      unlockableByAd: true,
    ),
    Cosmetic(
      id: 'character_ghost',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticGhost',
      rarity: Rarity.legendary,
      previewAsset: 'assets/cosmetics/character_ghost.png',
      priceGems: 400,
    ),
    Cosmetic(
      id: 'trail_dust',
      slot: CosmeticSlot.effect,
      nameKey: 'trailDust',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/trail_dust.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'trail_rainbow',
      slot: CosmeticSlot.effect,
      nameKey: 'trailRainbow',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/trail_rainbow.png',
      priceGems: 300,
    ),
    Cosmetic(
      id: 'trail_fire',
      slot: CosmeticSlot.effect,
      nameKey: 'trailFire',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/trail_fire.png',
      priceGems: 220,
    ),
    Cosmetic(
      id: 'trail_bubbles',
      slot: CosmeticSlot.effect,
      nameKey: 'trailBubbles',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/trail_bubbles.png',
      unlockableByAd: true,
    ),
    Cosmetic(
      id: 'trail_stars',
      slot: CosmeticSlot.effect,
      nameKey: 'trailStars',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/trail_stars.png',
      priceGems: 260,
    ),
    Cosmetic(
      id: 'background_sunny',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSunnyDay',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/background_sunny.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'background_sunset',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSunset',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/background_sunset.png',
      priceGems: 200,
    ),
    Cosmetic(
      id: 'background_neon',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundNeonNight',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/background_neon.png',
      priceGems: 320,
    ),
    Cosmetic(
      id: 'background_space',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSpace',
      rarity: Rarity.legendary,
      previewAsset: 'assets/cosmetics/background_space.png',
      priceGems: 450,
    ),
  ],
);
