import 'package:game_core/game_core.dart';

/// Blocko's store content (GAME_IDEAS.md §4.6): character skins, block
/// themes, and backgrounds. Preview art is not shipped yet — `CosmeticCard`
/// falls back to a rarity-colored icon when the asset is missing.
final StoreCatalog blockoCatalog = StoreCatalog(
  categories: const [
    StoreCategory(id: 'characters', nameKey: 'tabCharacters', slot: CosmeticSlot.character),
    StoreCategory(id: 'themes', nameKey: 'tabThemes', slot: CosmeticSlot.theme),
    StoreCategory(id: 'backgrounds', nameKey: 'tabBackgrounds', slot: CosmeticSlot.background),
  ],
  cosmetics: const [
    Cosmetic(
      id: 'character_classic',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticClassic',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/character_classic.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'character_robot',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticRobot',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/character_robot.png',
      priceGems: 150,
    ),
    Cosmetic(
      id: 'character_ninja',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticNinja',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/character_ninja.png',
      priceGems: 250,
    ),
    Cosmetic(
      id: 'character_panda',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticPanda',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/character_panda.png',
      unlockableByAd: true,
    ),
    Cosmetic(
      id: 'character_astronaut',
      slot: CosmeticSlot.character,
      nameKey: 'cosmeticAstronaut',
      rarity: Rarity.legendary,
      previewAsset: 'assets/cosmetics/character_astronaut.png',
      priceGems: 400,
    ),
    Cosmetic(
      id: 'theme_candy',
      slot: CosmeticSlot.theme,
      nameKey: 'themeCandy',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/theme_candy.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'theme_neon',
      slot: CosmeticSlot.theme,
      nameKey: 'themeNeon',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/theme_neon.png',
      priceGems: 200,
    ),
    Cosmetic(
      id: 'theme_wood',
      slot: CosmeticSlot.theme,
      nameKey: 'themeWood',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/theme_wood.png',
      priceGems: 150,
    ),
    Cosmetic(
      id: 'theme_fruit',
      slot: CosmeticSlot.theme,
      nameKey: 'themeFruit',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/theme_fruit.png',
      unlockableByAd: true,
    ),
    Cosmetic(
      id: 'theme_ice',
      slot: CosmeticSlot.theme,
      nameKey: 'themeIce',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/theme_ice.png',
      priceGems: 300,
    ),
    Cosmetic(
      id: 'background_sunny',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSunny',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/background_sunny.png',
      defaultOwned: true,
    ),
    Cosmetic(
      id: 'background_sky',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSky',
      rarity: Rarity.common,
      previewAsset: 'assets/cosmetics/background_sky.png',
      priceGems: 150,
    ),
    Cosmetic(
      id: 'background_sunset',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundSunset',
      rarity: Rarity.rare,
      previewAsset: 'assets/cosmetics/background_sunset.png',
      priceGems: 200,
    ),
    Cosmetic(
      id: 'background_galaxy',
      slot: CosmeticSlot.background,
      nameKey: 'backgroundGalaxy',
      rarity: Rarity.epic,
      previewAsset: 'assets/cosmetics/background_galaxy.png',
      priceGems: 350,
    ),
  ],
);
